EMP.Web/Controllers/ShipmentController.cs
using EMP.Common;
using EMP.Dto;
using EMP.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EMP.Web.Controllers
{
    public class ShipmentController : BaseController
    {
        private readonly IShipmentService service;

        public ShipmentController(IShipmentService _service)
        {
            this.service = _service;
        }
        public async Task<IActionResult> Index()
        {
            var response = await service.GetAllAsync<ResponseDto<List<ShipmentDto>>>();
            return View(response.Result);
        }
        public async Task<IActionResult> Create(Guid? id)
        {
            ViewBag.brokersList = Enum.GetValues(typeof(Brokers)).Cast<Brokers>().Select(x => new SelectListItem()
            {
                Text = x.GetDisplayName(),
                Value = ((int)x).ToString()
            }).ToList();
            if (id.HasValue)
            {
                var response = await service.GetByIdAsync<ResponseDto<ShipmentAddDto>>(id.Value);
                return View(response.Result);
            }

            return View(new ShipmentAddDto());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ShipmentAddDto model)
        {
            if (ModelState.IsValid)
            {
                model.EmpId = CurrentUser.UserId;
                var response = model.Id.HasValue ? await service.UpdateAsync<ResponseDto<string>>(model) : await service.CreateAsync<ResponseDto<string>>(model);
                if (response != null && response.IsSuccess)
                {
                    ShowSuccessMessage("Success",model.Id.HasValue? "Shipment updated" : "Shipment added", false);
                    return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Message = $"Shipmen {(model.Id.HasValue ? "update" : "save")} successfully", IsSuccess = true, RedirectUrl = "/Shipment/index" });
                }
            }
            ModelState.AddModelError("", "Validation failed");
            return CreateModelStateErrors();
        }

        public async Task<IActionResult> DeleteById(Guid id)
        {
            var response = await service.DeleteAsync<ResponseDto<string>>(id);
            ShowSuccessMessage("Success", "Shipment deleted", false);
            return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Message = "Shipment delete successfully", IsSuccess = true, RedirectUrl = "/Shipment/index" });
        }

        public async Task<IActionResult> UPDateToLive(Guid id)
        {
            var response = await service.UPDateToLiveAsync<ResponseDto<string>>(id);
            ShowSuccessMessage("Success", "Shipment updated to Live", false);
            return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Message = "Shipment delete successfully", IsSuccess = true, RedirectUrl = "/Shipment/index" });
        }

        public async Task<IActionResult> UPDateToNonLive(Guid id)
        {
            var response = await service.UPDateToNonLiveAsync<ResponseDto<string>>(id);
            ShowSuccessMessage("Success", "Shipment update to Non Live", false);
            return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Message = "Shipment delete successfully", IsSuccess = true, RedirectUrl = "/Shipment/index" });
        }
    }
}

EMP.Web/Views/Shipment/Create.cshtml
@model ShipmentAddDto

<style>
    .error {
        color: red;
    }

    .save-stngs ul li {
        width: auto;
    }

    .validation-summary-errors {
        color: red;
    }

    .save-stngs ul li a {
        display: inline-block;
        color: #000000;
        font-size: 16px;
        border: 1px solid #e5e5e5;
        height: 40px;
        line-height: 40px;
        padding: 0 22px;
        font-weight: 600;
        background: none;
        cursor: pointer;
    }
</style>

<div class="main-section">
    <div class="container">
        <div class="main-section-data">
            <div class="row">
                <div class="col-lg-3">

                </div>
                <div class="col-lg-6">

                    <div class="widget widget-user">
                        <h3 class="title-wd">Add/Edit Shipment</h3>
                        <form asp-action="Create" asp-controller="Shipment" method="post" id="frm-add-shipment">
                            <div id="validation-summary"></div>
                            <div class="cp-field">
                                <h5>Broker</h5>
                                <div class="cpp-fiel">
                                    <input type="hidden" asp-for="Id" />
                                    <select class="form-control" asp-for="Broker" data-msg-required="*required" data-rule-required="true" asp-items="ViewBag.brokersList">
                                        <option value=""> Select Broker</option>
                                    </select>
                                </div>
                            </div>
                            <div class="cp-field">
                                <h5>Trading Platform</h5>
                                <div class="cpp-fiel">
                                    <input type="text" asp-for="Platform" placeholder="Trading Platform" class="form-control" data-msg-required="*required" data-rule-required="true">

                                </div>
                            </div>

                            <div class="cp-field">
                                <h5> Trading Platform Login Id</h5>
                                <div class="cpp-fiel">
                                    <input type="text" asp-for="LoginId" placeholder="Trading Platform Login Id" class="form-control" data-msg-required="*required" data-rule-required="true">
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5> API Key</h5>
                                <div class="cpp-fiel">
                                    <input type="text" asp-for="APIKey" placeholder="API Key" class="form-control" data-msg-required="*required" data-rule-required="true">
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5> Password</h5>
                                <div class="cpp-fiel">
                                    <input type="password" asp-for="Password" placeholder="Password" class="form-control" data-msg-required="*required" data-rule-required="true" value="@Model.Password">
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5> Security Answer (2FA)</h5>
                                <div class="cpp-fiel">
                                    <input type="password" asp-for="Password2" placeholder="Security Answer (2FA)" class="form-control" data-msg-required="*required" data-rule-required="true" value="@Model.Password2">
                                </div>
                            </div>


                            <div class="save-stngs pd2">
                                <ul>
                                    <li><button type="button" style="background-color:green;"><i class="fa fa-arrow-right"></i> Validate</button></li>
                                    <li><button type="submit" style="background-color:lightseagreen;"><i class="fa fa-save"></i> Save</button></li>
                                    @if (Model.Id.HasValue)
                                    {
                        <li><a style="background-color:red;" href="javascript:void(0);" class="shipment-action" data-action="DeleteById" data-id="@Model.Id"> <i class="fa fa-trash"></i>Delete</a></li>}
                                </ul>
                            </div><!--save-stngs end-->
                        </form>

                    </div>


                </div>

                <div class="col-lg-3">

                </div>

            </div>
        </div><!-- main-section-data end-->
    </div>
</div>

@section Scripts{
    <script src="~/js/moment.js" asp-append-version="true"></script>
    <script src="~/js/google-chart-loader.js" asp-append-version="true"></script>
    <script src="~/js/Custom/Shipment_Addedit.js" asp-append-version="true"></script>
}

EMP.Web/Views/Shipment/Index.cshtml
@model List<ShipmentDto>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer



<div class="main-section">
    <div class="container">
        <div class="main-section-data">
            <div class="row">

                <div class="col-lg-12">
                    <div class="main-ws-sec">
                        <div class="posts-section">
                            <div class="post-bar">
                                <div class="post-st">
                                    <ul>
                                        <li><a href="/shipment/create" title="" style="background-color:cadetblue;">@Localizer["AddNew"]</a></li>
                                        <li><a href="javascript:void(0);" class="shipment-validate" title="" style="background-color:cadetblue;">@Localizer["ValidateAll"]</a></li>
                                        <li><a href="javascript:void(0);" class="shipment-action" data-action="UPDateToLive" data-message="Are you sure want to live !" title="" style="background-color:green;">@Localizer["Live"]</a></li>
                                        <li><a href="javascript:void(0);" class="shipment-action" data-action="UPDateToNonLive" data-message="Are you sure want to Non live !" title="" style="background-color:orange;">@Localizer["Non_Live"]</a></li>
                                        <li><a href="javascript:void(0);" class="shipment-action" data-action="DeleteById" data-message="Are you sure want to delete !" title="" style="background-color:red;">@Localizer["Delete"]</a></li>
                                    </ul>
                                </div>
                                <h3 class="title-wd">@Localizer["TradingAccount"]</h3>
                                <table class="table table-bordered" id="shipment_grid">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>@Localizer["LoginId"]</th>
                                            <th>@Localizer["PseudoAcc"]</th>
                                            <th>@Localizer["Live"]</th>
                                            <th>@Localizer["Broker"]</th>
                                            <th>@Localizer["Platform"]</th>
                                            <th>@Localizer["Expiry"]</th>
                                            <th>@Localizer["Day Left"]</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model != null && Model.Count > 0)
                                        {
                                            foreach (var item in Model)
                                            {
                            <tr>
                                <td>
                                    <input type="radio" name="radio_shipment" value="@item.Id" />
                                </td>
                                <td>
                                    <a href="/shipment/create/@item.Id">@item.LoginId</a>
                                </td>
                                <td>@item.LoginId</td>
                                <td>
                                    @if (item.IsLive)
                                    {
                                    <span style="color: green; font-size: 20px; font-weight: bold;">@Localizer["Yes"]</span> }
            else
            {
                                <span style="color: red; font-size: 20px; font-weight: bold;">@Localizer["No"]</span>}


                                </td>
                                <td>@(((Brokers)item.Broker).GetDisplayName())</td>
                                <td>@item.Platform</td>
                                <td>@item.Expiry.ToString("dd/MM/yyyy")</td>
                                <td>@(item.Expiry < DateTime.Now ? "-1" : (item.Expiry.Date - DateTime.Now.Date).TotalDays.ToString())</td>
                            </tr>
 }
                    }
                    else
                    {
        <tr>
            <td colspan="8">@Localizer["ItemNotFound"]</td>
        </tr>}
                                    </tbody>
                                </table>


                            </div>


                        </div>

                    </div><!--main-ws-sec end-->
                </div>

            </div>
        </div><!-- main-section-data end-->
    </div>
</div>

@section Scripts{
    <script src="~/js/moment.js" asp-append-version="true"></script>
    <script src="~/js/google-chart-loader.js" asp-append-version="true"></script>
    <script src="~/js/Custom/Shipment_index.js" asp-append-version="true"></script>
}