EMP.Web/Controllers/SchemeProfitLossController.cs
using EMP.Common;
using EMP.Dto;
using EMP.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EMP.Web.Controllers
{
    public class SchemeProfitLossController : BaseController
    {
        private readonly ISchemeProfitLossService service;
        private readonly IHostingEnvironment env;
        public SchemeProfitLossController(ISchemeProfitLossService _service, IHostingEnvironment _env)
        {
            this.service = _service;
            this.env = _env;
        }
        public async Task<IActionResult> Index(Guid groupId)
        {
            var response = await service.GetAllAsync<ResponseDto<List<SchemeProfitLossDto>>>(groupId);
            ViewBag.id = groupId;
            return View(response.Result);
        }
        public async Task<IActionResult> Create(Guid? id, Guid groupId, bool isRefresh)
        {
            var model = new SchemeProfitLossDto() { GroupId = groupId };
            if (id.HasValue)
            {
                var response = await service.GetByIdAsync<ResponseDto<SchemeProfitLossDto>>(id.Value);
                model = response.Result;

            }

            var keywordResponse = await service.GetKeywordsAsync<ResponseDto<List<string>>>();
            model.KeywordList = keywordResponse.Result.Select(x => new SelectedListItemMvcDto()
            {
                Text = x,
                Value = x
            }).ToList();
            model.IsRefresh = isRefresh;
            return PartialView("_AddEdit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SchemeProfitLossDto model)
        {
            if (ModelState.IsValid)
            {
                var resultIsExist = await service.IsExist<ResponseDto<bool>>(model.Id,model.GroupId,model.Date.Value);
                if (!resultIsExist.Result)
                {
                    var response = model.Id.HasValue ? await service.UpdateAsync<ResponseDto<string>>(model) : await service.CreateAsync<ResponseDto<string>>(model);
                    if (response != null && response.IsSuccess)
                    {
                        if(!model.IsRefresh)
                        ShowSuccessMessage("Success", model.Id.HasValue ? "Scheme Profit & Loss updated" : "Scheme Profit & Loss added", false);
                        return NewtonSoftJsonResult(new RequestOutcome<dynamic>
                        {
                            Message = model.Id.HasValue ? "Scheme Profit & Loss updated" : "Scheme Profit & Loss added",
                            IsSuccess = true,
                            Data = model.IsRefresh,
                            RedirectUrl = $"/SchemeProfitLoss/index?groupId={model.GroupId}"
                        });
                    }
                }
                else
                {
                    ModelState.AddModelError("", $"Alreday added for {model.Date.Value.ToString("dd/MM/yyyy")}");
                    return CreateModelStateErrors();
                }
                
            }

            ModelState.AddModelError("", "Validation failed");
            return CreateModelStateErrors();
        }

        public async Task<IActionResult> DeleteById(Guid id, Guid groupId)
        {
            var response = await service.DeleteAsync<ResponseDto<string>>(id);
            ShowSuccessMessage("Success", "Scheme Profit & Loss deleted", false);
            return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Message = "Scheme Profit & Loss delete successfully", IsSuccess = true, RedirectUrl = $"/SchemeProfitLoss/index?groupId={groupId}" });
        }

        public async Task<IActionResult> RestoreDefault(Guid groupId)
        {
            var webRoot = env.WebRootPath;
            string filePath = $"{webRoot}/js/Group_Chart.json";
            List<SchemeProfitLossDto> dataResponse = new List<SchemeProfitLossDto>();
            using (var sr = new StreamReader(filePath))
            {
                dataResponse = JsonConvert.DeserializeObject<List<GroupChartDto>>(sr.ReadToEnd()).OrderBy(o => o.Date).Select(x => new SchemeProfitLossDto()
                {
                    Date = x.Date,
                    Expense = 0,
                    ProfitLoss = x.DailyPnL,
                    GroupId = groupId
                }).ToList();
            }

            await service.AddRangeAsync<ResponseDto<string>>(dataResponse);


            return RedirectToAction("Index", new { groupId = groupId });

        }
    }
}

EMP.Web/Views/SchemeProfitLoss/Create.cshtml
@model SchemeProfitLossDto
@using Newtonsoft.Json

<script>
    function set(value) {
        return value;
    }
    var jsKeywordList = '@Model.KeywordList' == null ? "" : set(@Html.Raw(JsonConvert.SerializeObject(Model.KeywordList)));

</script>

<style>
    .error {
        color: red;
    }

    .save-stngs ul li {
        width: auto;
    }

    .validation-summary-errors {
        color: red;
    }

    .save-stngs ul li a {
        display: inline-block;
        color: #000000;
        font-size: 16px;
        border: 1px solid #e5e5e5;
        height: 40px;
        line-height: 40px;
        padding: 0 22px;
        font-weight: 600;
        background: none;
        cursor: pointer;
    }

    .toggle-btn {
        position: absolute;
        top: -35px;
        right: 21px;
    }

    .selectize-input {
        border: 1px solid #d0d0d0;
        padding: 8px 8px;
        display: inline-block;
        width: 106% !important;
        overflow: hidden;
        position: relative;
        z-index: 1;
        box-sizing: border-box;
        box-shadow: inset 0 1px 1px rgb(0 0 0 / 10%);
        border-radius: 3px;
        top: -7px;
        left: -13px;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/css/selectize.css" integrity="sha512-85w5tjZHguXpvARsBrIg9NWdNy5UBK16rAL8VWgnWXK2vMtcRKCBsHWSUbmMu0qHfXW2FVUDiWr6crA+IFdd1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="main-section">
    <div class="container">
        <div class="main-section-data">
            <div class="row">
                <div class="col-lg-3">

                </div>
                <div class="col-lg-6">

                    <div class="widget widget-user">
                        <h3 class="title-wd">Add/Edit Scheme Profit & Loss</h3>
                        <form asp-action="Create" asp-controller="SchemeProfitLoss" method="post" id="frm-add-SchemeProfitLoss">
                            <div id="validation-summary"></div>
                            
                            <div class="cp-field">
                                <h5>Broker</h5>
                                <div class="cpp-fiel">
                                    <input type="hidden" asp-for="Id" />
                                    <input type="hidden" asp-for="GroupId" />
                                    <input type="date" asp-for="Date" placeholder="Date" class="form-control" data-msg-required="*required" data-rule-required="true">
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5>KeyWord</h5>
                                <div class="cpp-fiel">
                                    <input type="text" asp-for="KeyWord" class="form-control">
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5> Profit & Loss</h5>
                                <div class="cpp-fiel">
                                    <input type="text" asp-for="ProfitLoss" placeholder="Profit & Loss" class="form-control" data-msg-required="*required" data-rule-required="true">
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5> Expense</h5>
                                <div class="cpp-fiel">
                                    <input type="text" asp-for="Expense" placeholder="Expense" class="form-control" data-msg-required="*required" data-rule-required="true">
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5>Comments</h5>
                                <div class="cpp-fiel">
                                    <textarea asp-for="Comments" placeholder="Comments" class="form-control" cols="5" rows="5"></textarea>
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5>No TradeDay</h5>
                                <div class="cpp-fiel">
                                    <div class="toggle-btn">
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" asp-for="IsNoTradeDay">
                                            <label class="custom-control-label" for="IsNoTradeDay"></label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5>Holiday</h5>
                                <div class="cpp-fiel">
                                    <div class="toggle-btn">
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" asp-for="IsHoliday">
                                            <label class="custom-control-label" for="IsHoliday"></label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="save-stngs pd2">
                                <ul>
                                    <li><button type="submit" style="background-color:lightseagreen;"><i class="fa fa-save"></i> Save</button></li>
                                    <li><a href="/SchemeProfitLoss/index?groupId=@Model.GroupId"><i class="fa fa-backward"></i> Back</a></li>
                                </ul>
                            </div>

                        </form>

                    </div>


                </div>

                <div class="col-lg-3">

                </div>

            </div>
        </div><!-- main-section-data end-->
    </div>
</div>

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/js/standalone/selectize.js" integrity="sha512-pF+DNRwavWMukUv/LyzDyDMn8U2uvqYQdJN0Zvilr6DDo/56xPDZdDoyPDYZRSL4aOKO/FGKXTpzDyQJ8je8Qw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/Custom/SchemeProfitLoss.js" asp-append-version="true"></script>
}

EMP.Web/Views/SchemeProfitLoss/Index.cshtml
@model List<SchemeProfitLossDto>
@{ Guid groupId = ViewBag.id; }

<div class="main-section">
    <div class="container">
        <div class="main-section-data">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-ws-sec">
                        <div class="posts-section">
                            <div class="post-bar">
                                <div class="post-st">
                                    <ul>

                                        <li>
                                            <a href="/SchemeProfitLoss/Create?groupId=@groupId" style="background-color:cadetblue;" data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#modal-add-edit-schemeporfitloss" class="btn btn btn-primary add"><i class="fa fa-plus"></i> Add New</a>
                                        </li>
                                        @if (Model == null || !Model.Any())
                                        {
                                    <li><a href="/SchemeProfitLoss/RestoreDefault?groupId=@groupId" title="" style="background-color:cadetblue;">Restore default Data</a></li>
}

                                        <li>
                                            <a href="/employeegroup/view/@groupId" class="btn"><i class="fa fa-backward"></i> Back</a>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="title-wd">Profit & Loss</h3>
                                <table class="table table-bordered" id="schemeprofitloss_grid">
                                    <thead>
                                        <tr>

                                            <th>Date</th>
                                            <th>Profit & Loss</th>
                                            <th>Expense</th>
                                            <th>KeyWord</th>
                                            <th>Comments</th>
                                            <th>IsNoTradeDay</th>
                                            <th>IsHoliday</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model != null && Model.Count > 0)
                                        {
                                            foreach (var item in Model)
                                            {
                            <tr>
                                <td>
                                    @item.Date.Value.ToString("dd/MM/yyyy")
                                </td>
                                <td>
                                    @item.ProfitLoss
                                </td>
                                <td>@item.Expense</td>
                                <td>@item.KeyWord</td>
                                <td>@item.Comments</td>
                                <td>
                                    @if (item.IsNoTradeDay)
                                    {
                <span style="color: green; font-size: 20px; font-weight: bold;">Yes</span> }
            else
            {
<span style="color: red; font-size: 20px; font-weight: bold;">No</span>}


                                </td>
                                <td>
                                    @if (item.IsHoliday)
                                    {
                <span style="color: green; font-size: 20px; font-weight: bold;">Yes</span> }
            else
            {
<span style="color: red; font-size: 20px; font-weight: bold;">No</span>}


                                </td>
                                <td>
                                    <a href="/SchemeProfitLoss/create/@item.Id?groupId=@item.GroupId"><i class="fa fa-pencil"></i></a>
                                    &ensp;&ensp;
                                    <a href="javasript:void(0);" class="shipment-action" data-groupid="@item.GroupId" data-id="@item.Id" data-message="Are you sure want to delete !"><i class="fa fa-trash"></i></a>
                                </td>

                            </tr> }
                                        }
                                        else
                                        {
                            <tr>
                                <td colspan="8">Data Not Found</td>
                            </tr>
}
                                    </tbody>
                                </table>


                            </div>


                        </div>

                    </div><!--main-ws-sec end-->
                </div>

            </div>
        </div><!-- main-section-data end-->
    </div>
</div>


@Html.Partial("_Modal", new Modal { ID = "modal-add-edit-schemeporfitloss", AreaLabeledId = "modal-add-edit-schemeporfitloss-label", Size = ModalSize.Medium })

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/js/standalone/selectize.js" integrity="sha512-pF+DNRwavWMukUv/LyzDyDMn8U2uvqYQdJN0Zvilr6DDo/56xPDZdDoyPDYZRSL4aOKO/FGKXTpzDyQJ8je8Qw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/Custom/SchemeProfitLoss.js" asp-append-version="true"></script>
    <script src="~/js/Custom/SchemeProfitLoss-AddEdit.js" asp-append-version="true"></script>
}

EMP.Web/Views/SchemeProfitLoss/_AddEdit.cshtml
@model SchemeProfitLossDto
@using Newtonsoft.Json

<script>
    function set(value) {
        return value;
    }
    var jsKeywordList = '@Model.KeywordList' == null ? "" : set(@Html.Raw(JsonConvert.SerializeObject(Model.KeywordList)));

</script>

<style>
    .error {
        color: red;
    }

    .save-stngs ul li {
        width: auto;
    }

    .validation-summary-errors {
        color: red;
    }

    .save-stngs ul li a {
        display: inline-block;
        color: #000000;
        font-size: 16px;
        border: 1px solid #e5e5e5;
        height: 40px;
        line-height: 40px;
        padding: 0 22px;
        font-weight: 600;
        background: none;
        cursor: pointer;
    }

    .toggle-btn {
        position: absolute;
        top: -35px;
        right: 21px;
    }

    .selectize-input {
        border: 1px solid #d0d0d0;
        padding: 8px 8px;
        display: inline-block;
        width: 106% !important;
        overflow: hidden;
        position: relative;
        z-index: 1;
        box-sizing: border-box;
        box-shadow: inset 0 1px 1px rgb(0 0 0 / 10%);
        border-radius: 3px;
        top: -7px;
        left: -13px;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/css/selectize.css" integrity="sha512-85w5tjZHguXpvARsBrIg9NWdNy5UBK16rAL8VWgnWXK2vMtcRKCBsHWSUbmMu0qHfXW2FVUDiWr6crA+IFdd1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />


<div id="frm-add-SchemeProfitLoss" class="box">
    <form asp-action="Create" asp-controller="SchemeProfitLoss" method="post">
        @Html.Partial("_ModalHeader", new ModalHeader { Heading = "Add/Edit Scheme Profit & Loss" })
        
        <div class="modal-body">
            <div id="validation-summary"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="GroupId" />
            <input type="hidden" asp-for="IsRefresh" />
            <div class="cp-field">
                <h5>Broker</h5>
                <div class="cpp-fiel">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="GroupId" />
                    <input type="date" asp-for="Date" placeholder="Date" class="form-control" data-msg-required="*required" data-rule-required="true">
                </div>
            </div>

            <div class="cp-field">
                <h5>KeyWord</h5>
                <div class="cpp-fiel">
                    <input type="text" asp-for="KeyWord" class="form-control">
                </div>
            </div>

            <div class="cp-field">
                <h5> Profit & Loss</h5>
                <div class="cpp-fiel">
                    <input type="text" asp-for="ProfitLoss" placeholder="Profit & Loss" class="form-control" data-msg-required="*required" data-rule-required="true">
                </div>
            </div>

            <div class="cp-field">
                <h5> Expense</h5>
                <div class="cpp-fiel">
                    <input type="text" asp-for="Expense" placeholder="Expense" class="form-control" data-msg-required="*required" data-rule-required="true">
                </div>
            </div>

            <div class="cp-field">
                <h5>Comments</h5>
                <div class="cpp-fiel">
                    <textarea asp-for="Comments" placeholder="Comments" class="form-control" cols="5" rows="5"></textarea>
                </div>
            </div>

            <div class="cp-field">
                <h5>No TradeDay</h5>
                <div class="cpp-fiel">
                    <div class="toggle-btn">
                        <div class="custom-control custom-switch">
                            <input type="checkbox" class="custom-control-input" asp-for="IsNoTradeDay">
                            <label class="custom-control-label" for="IsNoTradeDay"></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="cp-field">
                <h5>Holiday</h5>
                <div class="cpp-fiel">
                    <div class="toggle-btn">
                        <div class="custom-control custom-switch">
                            <input type="checkbox" class="custom-control-input" asp-for="IsHoliday">
                            <label class="custom-control-label" for="IsHoliday"></label>
                        </div>
                    </div>
                </div>
            </div>

            @*<div class="save-stngs pd2">
            <ul>
                <li><button type="submit" style="background-color:lightseagreen;"><i class="fa fa-save"></i> Save</button></li>
                <li><a href="/SchemeProfitLoss/index?groupId=@Model.GroupId"><i class="fa fa-backward"></i> Back</a></li>
            </ul>
        </div>*@

        </div>
        @Html.Partial("_ModalFooter", new ModalFooter { })
    </form>
</div>