EMP.Web/Controllers/EmployeeGroupController.cs
using EMP.Dto;
using EMP.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EMP.Web.Controllers
{
    public class EmployeeGroupController : BaseController
    {
        private readonly IEmployeeGroupService service;
        private readonly IEmployeeService employeeService;
        private readonly ISchemeProfitLossService schemeProfitLossService;
        private readonly IHostingEnvironment env;
        public EmployeeGroupController(IEmployeeGroupService _service, IEmployeeService _employeeService,
            IHostingEnvironment _env, ISchemeProfitLossService _schemeProfitLossService)
        {
            this.service = _service;
            this.employeeService = _employeeService;
            this.env = _env;
            this.schemeProfitLossService = _schemeProfitLossService;
        }
        public async Task<IActionResult> Index()
        {
            var allEmpService = await employeeService.GetAllEmployeeAsync<ResponseDto<List<EmployeeDto>>>();
            var empList = allEmpService.Result.Where(x => x.Id != CurrentUser.UserId).Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList();
            ViewBag.empList = empList;
            return View();
        }

        public async Task<IActionResult> BindGrid(int pageNo = 1, int pageSize = 5)
        {

            var response = await service.GetPageEmployeeGroupAsync<ResponseDto<EmployeeGroupGridlDto>>(CurrentUser.UserId, pageNo, pageSize);
            return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Data = response.Result, IsSuccess = true });
        }

        public async Task<IActionResult> BindEmpDrop()
        {

            var allEmpService = await employeeService.GetAllEmployeeAsync<ResponseDto<List<EmployeeDto>>>();
            var empList = allEmpService.Result.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() }).ToList();
            return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Data = empList, IsSuccess = true });
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeGroupAddDto model)
        {
            model.AdminId = CurrentUser.UserId;
            if (ModelState.IsValid)
            {

                var allFiles = this.Request.Form.Files;
                if (allFiles != null && allFiles.Any() && allFiles["ImageURLFile"] != null)
                {
                    var profileImage = allFiles["ImageURLFile"];
                    var profileExten = new[] { ".jpg", ".png", ".jpeg" };
                    var ext = Path.GetExtension(profileImage.FileName).ToLower();
                    if (!profileExten.Contains(ext))
                    {
                        ModelState.AddModelError("", $"Grpop image not valid, Please choose jpg,png,jpeg format");
                        return CreateModelStateErrors();
                    }
                    else
                    {
                        model.IconImg = await this.UploadFiles(env, profileImage, model.IconImg, "GroupImage");
                    }
                }
                else
                {
                    ModelState.AddModelError("", $"Grpop image is required");
                    return CreateModelStateErrors();
                }


                var response = model.Id.HasValue ? await service.UpdateEmployeeGroupAsync<ResponseDto<string>>(model) : await service.CreateEmployeeGroupAsync<ResponseDto<string>>(model);
                if (response != null && response.IsSuccess)
                {
                    return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Message = $"Employee group {(model.Id.HasValue ? "update" : "save")} successfully", IsSuccess = true, RedirectUrl = "/employeegroup/index" });
                }
            }
            ModelState.AddModelError("", "Validation failed");
            return CreateModelStateErrors();
        }

        public async Task<IActionResult> GetById(Guid id)
        {
            var response = await service.GetEmployeeGroupByIdAsync<ResponseDto<EmployeeGroupListDto>>(id);
            return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Data = response.Result, IsSuccess = true });
        }

        public async Task<IActionResult> DeleteById(Guid id)
        {
            var response = await service.DeleteEmployeeGroupAsync<ResponseDto<string>>(id);
            return NewtonSoftJsonResult(new RequestOutcome<dynamic> { Message = "Employee group delete successfully", IsSuccess = true });
        }

        public async Task<IActionResult> GetAllGroupForSubscription(Guid id)
        {
            var response = await service.GetAllGroupForSubscription<ResponseDto<List<SelectedListItemDto>>>(id);
            return NewtonSoftJsonResult(new RequestOutcome<List<SelectedListItemDto>> { Data = response.Result, IsSuccess = true });
        }

        public async Task<IActionResult> View(Guid id)
        {
            var response = await service.GetGroupForView<ResponseDto<EmployeeGroupForApprovalListDto>>(id);
            ViewBag.dateList = GetTransctionList().Select(x => new SelectListItem() { Text = x.EntryDate.ToString("dd/MM/yyyy"), Value = x.EntryDate.ToString("MM/dd/yyyy") }).ToList();
            return View(response.Result);
        }

        public async Task<IActionResult> GetTransction(DateTime? from)
        {

            List<GroupTransactionDto> dataResponse = GetTransctionList();

            if (from.HasValue)
            {
                dataResponse = dataResponse.Where(x => x.EntryDate == from).ToList();
            }
            return NewtonSoftJsonResult(new RequestOutcome<List<GroupTransactionDto>> { Data = dataResponse, IsSuccess = true });
        }

        public List<GroupTransactionDto> GetTransctionList()
        {
            var webRoot = env.WebRootPath;
            string filePath = $"{webRoot}/js/GroupTransaction.json";
            List<GroupTransactionDto> dataResponse = new List<GroupTransactionDto>();
            using (var sr = new StreamReader(filePath))
            {
                return JsonConvert.DeserializeObject<List<GroupTransactionDto>>(sr.ReadToEnd()).OrderBy(o => o.EntryDate).ToList();
            }

        }

        public async Task<IActionResult> GetChartData(Guid groupId, DateTime? fromDate, DateTime? toDate, int typeId = 1)
        {
            var response = await schemeProfitLossService.GetChartAsync<ResponseDto<List<GroupChartDto>>>(groupId, typeId,fromDate,toDate);
            return NewtonSoftJsonResult(new RequestOutcome<List<GroupChartDto>> { Data = response.Result, IsSuccess = true });
        }

        public async Task<IActionResult> GetProfitLossChartData(Guid groupId, DateTime? fromDate, DateTime? toDate, int typeId = 1)
        {
            var response = await schemeProfitLossService.GetProfitLossChartAsync<ResponseDto<List<GroupChartDto>>>(groupId, typeId,fromDate,toDate);
            return NewtonSoftJsonResult(new RequestOutcome<List<GroupChartDto>> { Data = response.Result, IsSuccess = true });
        }

        public async Task<IActionResult> GetMonthlyBreaupData(Guid groupId, DateTime? fromDate, DateTime? toDate)
        {
            var response = await schemeProfitLossService.GetMonthlyBreaupAsync<ResponseDto<List<GroupMontlyBreakupDto>>>(groupId,fromDate,toDate);
            return NewtonSoftJsonResult(new RequestOutcome<List<GroupMontlyBreakupDto>> { Data = response.Result, IsSuccess = true });
        }

        public async Task<IActionResult> GetCal_HeatmapData(Guid groupId, DateTime fromDate, DateTime toDate)
        {
            var response = await schemeProfitLossService.GetCal_HeatmapDataAsync<ResponseDto<List<HeatmapResponseDto>>>(groupId, fromDate, toDate);
            return Json(response.Result);
        }

        public async Task<IActionResult> GetPLSummary(Guid groupId, DateTime? fromDate, DateTime? toDate)
        {
            var response = await schemeProfitLossService.GetPLSummaryAsync<ResponseDto<SchemeProfitLossSummaryDto>>(groupId, fromDate, toDate);
            return Json(response.Result);
        }

    }
}

EMP.Web/Views/EmployeeGroup/Index.cshtml
<style>
    .quest-tags li {
        margin-bottom: 5px;
    }

    .usr_img {
        width: 56px;
    }

    .forum-page {
        padding: 0px 0;
    }

    .error {
        color: red;
    }

    .select2-selection__choice__display {
        float: none !important;
    }

    .select2-selection__choice {
        width: auto !important;
    }

</style>

<link rel="stylesheet" type="text/css" href="~/plugins/Select2/css/select2.min.css">

<section class="forum-page">
    <div class="container">
        <div class="forum-questions-sec">
            <div class="row">
                <div class="col-lg-7">
                    <div class="forum-questions">
                    </div>

                    <nav aria-label="Page navigation example" class="full-pagi">
                        <ul class="pagination">
                           
                        </ul>
                    </nav>

                </div>

                <div class="col-lg-5">
                    <div class="widget widget-user">
                        <h3 class="title-wd">Add/Edit Scheme</h3>
                        <form asp-action="Create" asp-controller="EmployeeGroup" method="post" id="frm-add-group">
                            <div id="validation-summary"></div>
                            <div class="cp-field">
                                <h5>Scheme Name</h5>
                                <div class="cpp-fiel">
                                    <input type="hidden" name="Id" id="group_id" />
                                    <input type="text" name="Name" id="group_name" placeholder="Scheme Name" class="form-control" data-msg-required="*required" data-rule-required="true">
                                </div>
                            </div>
                            <div class="cp-field">
                                <h5>Scheme Description</h5>
                                <div class="cpp-fiel">
                                    <input type="hidden" name="Id" id="group_id" />
                                    <textarea name="Description" id="group_description" placeholder="Scheme Description" class="form-control" data-msg-required="*required" data-rule-required="true"></textarea>
                                    
                                </div>
                            </div>

                            <div class="cp-field">
                                <h5> Invite Employees</h5>
                                <div class="cpp-fiel">
                                    <select name=EmployeeIds id="emp_select" class=form-control multiple data-msg-required="*required" data-rule-required="true">
                                        @foreach (SelectListItem item in ViewBag.empList)
                                        {
                                            <option value="@item.Value">@item.Text</option>
                                        }

                                    </select>
                                </div>
                            </div>

                             <div class="cp-field">
                                 <h5>Scheme Image</h5>
                                <div class="cpp-fiel">
                                    <input type="hidden" name="imageURL" id="employee_imageURL" />
                                    <input type="file" name="ImageURLFile" id="ImageURLFile" data-msg-required="*required" data-rule-required="true">
                                 <img src="/GroupImage/" id="view_ImageURLFile" style="width:50px;height:50px;display:none;" /> 
                                </div>
                            </div>

                            <div class="save-stngs pd2">
                                <ul>
                                    <li><button type="submit">Create Scheme</button></li>

                                </ul>
                            </div><!--save-stngs end-->
                        </form>

                    </div>

                </div>

            </div>
        </div>
    </div>
</section>


@section Scripts{
<script src="~/plugins/Select2/js/select2.min.js" asp-append-version="true"></script>
<script src="~/js/Custom/EmpGroup.js" asp-append-version="true"></script>
}